openapi: 3.0.0
info:
  title: Additional OpenAPI spec for interacting with the Nuts APIs.
  version: 1.0.0

components:
  schemas:
    ID:
      type: string
      description: Identifies the subject of the credential. In other words, the ID of the entity to which the credential was issued. Generally a Nuts DID.
    Organization:
      type: object
      properties:
        "name":
          description: The name of the organization.
          type: string
        "city":
          description: The city of the organization.
          type: string
    NutsOrganizationCredential:
      type: object
      description: A credential according to the W3C and Nuts specs.
      required:
        - "id"
        - "organization"
      properties:
        "id":
          $ref: '#/components/schemas/ID'
        "organization":
          $ref: '#/components/schemas/Organization'

    NutsAuthorizationCredential:
      type: object
      description: A credential according to the W3C and Nuts specs.
      required:
        - id
        - purposeOfUse
        - subject
      properties:
        "id":
          $ref: '#/components/schemas/ID'
        "purposeOfUse":
          description: Generally an access policy as defined by the Bolt.
          type: string
        "subject":
          type: string
          description: Identifier of the patient (Dutch Social Security Number).
        "legalBase":
          $ref: '#/components/schemas/LegalBase'
        "resources":
          description: The FHIR resources that can be accessed using the credential.
          type: array
          items:
            $ref: '#/components/schemas/FHIRResource'
    LegalBase:
      type: object
      description: The legal base of the credential.
      required:
        - "consentType"
      properties:
        "consentType":
          type: string
          enum: [ "implied", "explicit" ]
        "evidence":
          description: The evidence of the consent, if consentType is explicit.
          type: object
          properties:
            "path":
              type: string
            "type":
              type: string
    FHIRResource:
      type: object
      required:
        - path
        - operations
      properties:
        "path":
          description: The path of the resource.
          type: string
          example: /Task/1
        "operations":
          description: The FHIR operations that are allowed on the resource.
          type: array
          items:
            type: string
        "userContext":
          description: Indicates whether access to the resource requires an authenticated user.
          type: boolean

# Required to make it a valid OpenAPI spec (can be removed when migrating to OAS 3.1.0):
paths:
  /bogus:
    get:
      operationId: bogus
      responses:
        "200":
          description: Bogus